config/routes.rb
Dating::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root              :to => 'pages#home'

  match '/login',   :to => 'pages#home'
  match '/signup',  :to => 'pages#home'
  match '/inbox',   :to => 'messages#index', :as => :inbox
  match '/outbox',  :to => 'messages#outbox', :as => :outbox

  match '/logout', :to => 'sessions#destroy', :as => :logout

  resources :users do
    member do
      get :home
      get :matches, :interested
      get :find_matches
      resources :interests
    end
    collection do
      get 'search'
    end

    resources :messages
  end
  

  resources :sessions, only: [:create, :destroy]
  resources :relationships, except: [:edit, :update] # matches
 
  

  resources :messages, :singular => :message

  match '/:controller(/:action(/:id))(.:format)'
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :user_id, :sender_id, :time, :read, :msg_type, :message
  
  belongs_to :user

end

app/models/messages.rb
class Messages < ActiveRecord::Base
  belongs_to :relationship
end

# == Schema Information
#
# Table name: messages
#
#  id              :integer         not null, primary key
#  relationship_id :integer
#  message         :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  attr_accessor :type
  # GET /messages.json
  def index
    @user = User.find(session[:user_id])
    @messages = @user.messages
    # @messages = Message.where(:user_id => session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])
    @user = User.find(session[:user_id])
    
    if (!@message.read) then
      @message.read = true
      @message.save
    end 
    #print "sender: #{@message.user_id}"
    
    respond_to do |format|
      #if (@message.user_id != @user.id) then
      #  render '/shared/no_access'
      #else 
        format.html # show.html.erb
        format.json { render json: @message }
      #end
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
  
  def outbox
    #@user = User.find(session[:user_id])
    #@messages = @user.messages
    @messages = Message.where(:sender_id => session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end
  
  
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for @message, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Message</legend>

    <div class="control-group">
      <%= f.label :user_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :user_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :sender_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :sender_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :read, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :read, :class => 'check_box' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :msg_type, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :msg_type, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :message, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :message, :class => 'text_area' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', messages_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/messages/edit.html.erb
<%= render :partial => 'form' %>

app/views/messages/index.html.erb
<h1>Messages</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.id %></td>
        <td><%= link_to message.user_id, message_path(message) %></td>
        <td><%= message.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_message_path(message), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', message_path(message), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_message_path, :class => 'btn btn-primary' %>

app/views/messages/new.html.erb
<%= render :partial => 'form' %>

app/views/messages/outbox.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Recipient</th>
    <th>Sender</th>
    <th>Read</th>
    <th>Msg Type</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.user_id %></td>
    <td><%= message.sender_id %></td>
    <td><%= message.read %></td>
    <td><%= message.msg_type %></td>
    <td><%= message.message %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/show.html.erb
<h1>/Message</h1>

<p>
  <b>User</b><br>
  <%= @message.user_id %>
</p>

<p>
  <b>Sender</b><br>
  <%= @message.sender_id %>
</p>

<p>
  <b>Read</b><br>
  <%= @message.read %>
</p>

<p>
  <b>Msg type</b><br>
  <%= @message.msg_type %>
</p>

<p>
  <b>Message</b><br>
  <%= @message.message %>
</p>

<div class="form-actions">
  <%= link_to 'Back', messages_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_message_path(@message), :class => 'btn' %>
  <%= link_to 'Delete', message_path(@message), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>