config/routes.rb
Dating::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root              :to => 'pages#home'

  match '/login',   :to => 'pages#home'
  match '/signup',  :to => 'pages#home'
  match '/inbox',   :to => 'messages#index', :as => :inbox
  match '/outbox',  :to => 'messages#outbox', :as => :outbox

  match '/logout', :to => 'sessions#destroy', :as => :logout

  resources :users do
    member do
      get :home
      get :matches, :interested
      get :find_matches
      resources :interests
    end
    collection do
      get 'search'
    end

    resources :messages
  end
  

  resources :sessions, only: [:create, :destroy]
  resources :relationships, except: [:edit, :update] # matches
 
  

  resources :messages, :singular => :message

  match '/:controller(/:action(/:id))(.:format)'
end

app/views/shared/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
    <div class="alert alert-error alert-block">
      <strong>Oops!</strong>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.mobile.erb
<% if object && object.errors.size > 0 %>
  <div class="error">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.each do |key,value| %>
    <div class="flash <%= key %>"><%= value %> </div>
  <% end %>
<% end %>

app/views/shared/_match_stats.html.erb
<a href="<%= matches_user_path(@user) %>">
  <strong >
    <%= @user.matches.count %>
  </strong>
  <%= "people wanted by #{@user.name}" %>
</a>
<br />
<a href="<%= interested_user_path(@user) %>">
  <strong>
    <%= @user.interested_users.count %>  
  </strong>
  <%= "people want #{@user.name}" %>
</a>

app/views/shared/no_access.html.erb
<p>You do not have access to this page.</p>