config/routes.rb
Dating::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root              :to => 'pages#home'

  match '/login',   :to => 'pages#home'
  match '/signup',  :to => 'pages#home'
  match '/inbox',   :to => 'messages#index', :as => :inbox
  match '/outbox',  :to => 'messages#outbox', :as => :outbox

  match '/logout', :to => 'sessions#destroy', :as => :logout

  resources :users do
    member do
      get :home
      get :matches, :interested
      get :find_matches
      resources :interests
    end
    collection do
      get 'search'
    end

    resources :messages
  end
  

  resources :sessions, only: [:create, :destroy]
  resources :relationships, except: [:edit, :update] # matches
 
  

  resources :messages, :singular => :message

  match '/:controller(/:action(/:id))(.:format)'
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user

  validates :name, :presence => true


end

# == Schema Information
#
# Table name: interests
#
#  id         :integer         not null, primary key
#  interest   :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  name       :string(255)
#  user_id    :integer
#

app/models/interests.rb
class Interests < ActiveRecord::Base
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

  def index
    @user = User.find(session[:user_id])
    @title = "All interests for #{@user.name}"
    @interests = @user.interests
  end

  def create
    @user = User.find(session[:user_id])
    interest_name = params[:interest].values.first
    # @interest = Interest.new(:user_id => @user.id, :name => interest_name)
    @user.add_interest!( interest_name )

    flash.now[:success] = "Interest added"
    render 'new'
  end

  def new
    @user = User.find(session[:user_id])
    @title = 'Find new matches'
  end

  def destroy
    interest = Interest.find(params[:id])
    # check the interest is owned by the logged in user
    if interest.user_id == session[:user_id]
      interest.destroy
      flash.now[:success] = "Removed interest"
    else
      flash.now[:error] = "Cannot delete unowned interest. Are you logged in?"
    end
    render 'new'
  end




end

app/views/interests/_interest.html.erb
<li>
  <span>
    <%= interest.name %>  
    <!-- Only shows the destroy link if we're on an interests page and the interest belongs to the user -->
    <%= link_to_if( controller.controller_name == 'interests' && interest.user_id == session[:user_id], 'Remove', interest_path(@user.id, interest.id), method: :delete ) {} %>
  </span>
</li>

app/views/interests/_random_interests.html.erb
<ul class="interests">
  <% Interest.random(10).each do |interest| %>
    <%= render interest %>
  <% end %>
</ul>

app/views/interests/index.html.erb
<h1>All interests</h1>

<ul class="interests">
  <% @interests.each do |interest| %>
    <%= render interest %>
  <% end %>
</ul>

app/views/interests/new.html.erb
<h2>Add some interests to get more matches</h2>
<%= form_for(:interest, :as => :post, :url => interests_path(@user)) do |f| -%>
<div class="field">
  <%= f.label :name, 'Interest' %>
  <%= f.text_field :name %>
</div>

<div class="actions">
  <%= f.submit "Add" %>
</div>
<% end -%>


<br />
<h3>Current interests</h3>
<%= render 'users/user_interests' %>

<% content_for :sidebar do %>
  <h3>Can't think of anything?</h3>
  <p>Here are some interests entered by other users of <em>Coitus Cupid</em></p>
  <%= render 'random_interests' %>
<% end -%>