config/routes.rb
Dating::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root              :to => 'pages#home'

  match '/login',   :to => 'pages#home'
  match '/signup',  :to => 'pages#home'
  match '/inbox',   :to => 'messages#index', :as => :inbox
  match '/outbox',  :to => 'messages#outbox', :as => :outbox

  match '/logout', :to => 'sessions#destroy', :as => :logout

  resources :users do
    member do
      get :home
      get :matches, :interested
      get :find_matches
      resources :interests
    end
    collection do
      get 'search'
    end

    resources :messages
  end
  

  resources :sessions, only: [:create, :destroy]
  resources :relationships, except: [:edit, :update] # matches
 
  

  resources :messages, :singular => :message

  match '/:controller(/:action(/:id))(.:format)'
end

app/views/layouts/_header.html.erb
<header>
	<%= if session[:user_id].nil? %>
  		<%=  link_to logo, root_path %>
  	<%= else %>
  		<%= link_to logo, :url => {:controller => 'users', :id => session[:user_id], :action => 'home'} %>
  	<% end %>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Edit Profile", ed %></li>
        <li><%= link_to "Sign in", user_path %></li>
      </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= title %></title>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim to support IE6-8 -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

</head>

<body>
<div class="container">

  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">

        <%= link_to "Coitus Cupid", home_user_path(session[:user_id]), :class => 'brand' %> 
        <ul class="nav">
          <li><%= link_to "Dashboard", home_user_path(session[:user_id] )  %></li>
          <li><%= link_to "Show profile", user_path(session[:user_id] )  %></li>
          <li><%= link_to "New Matches", find_matches_user_path(session[:user_id])  %></li>
          <li><%= link_to "Inbox", inbox_path %></li>
        </ul>
        
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <li><%= link_to "Logout", logout_path %></li>
        </ul>
        <%= render('users/search_form') %>

      </div>
    </div>
  </div>


  <div class="row">
    <div class="span12">
      <%= flash_block %>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <%= yield :heading %>
    </div>
  </div>

  <div class="row">
    <div class="span5">
      <%= yield :sidebar %> 
    </div>
    <div class="span7">
      <%= yield %>
    </div>
  </div>


  <footer>
    <%= yield :footer %>
  </footer>
</div>

<!-- Loads faster with JS at the end -->
<%= javascript_include_tag "application" %>


<%= debug(params) if Rails.env.development? %>

</div>
</body>
</html>